1+1
f<-data.frame(2,"a")
## 1
air<- datasets::airquality
air[,2:4]
air[5,c(2,4)]
air$Wind
summary(air)
summary(air$wind)
#plot(airquality$Wind)
plot(airquality$Wind)
plot(air$Temp)
plot(air$Temp,air$Solar.R,air$Ozone,type="p")
plot(air$Ozone ,air$Temp , type = "p")
plot(air$Ozone, xlab = 'concentration of water',ylab = 'depth of water',type = "l",col=('red'))
barplot(air$Ozone ,main = "ozone air", xlab = "concentation" ,ylab = 'depth ' , col = "red" , horiz = F, axes = T )
hist(air$Ozone,col = "blue")        
hist(air$Solar.R, main = "solar",xlab = "earth" ,ylab = "sky",col = "red")
boxplot(air$Ozone)
boxplot(air$Wind)
boxplot(air$Wind,air$Ozone ,col = c("red","blue"), main ="combine")
boxplot(air[,1:4])
boxplot(air[2:20,1:3])
hist(air[5,4])
barplot(air[,4])
par(mfrow = c(4,4),mar=c(2,2,3,3), las=0, bty="o")
plot(air$Ozone)
plot(air$Solar.R,air$Ozone)
plot(air$Ozone,type = 'l')
plot(air$Wind,type = 'p')
barplot(air$Ozone,xlab = "concentration",ylab = "depth",col = "red")
boxplot(air$Ozone)
hist(air$Ozone)
sd(air$Ozone,na.rm = T)
var(air$Wind)
var(air$Wind ,na.rm = F)
var(air$Wind ,na.rm = T)
skewness(air$Temp)
kurtosis(air$Solar.R ,na.rm=T)
##2
e_quakes<-datasets::quakes
head(e_quakes,20)
sd(airquality$Ozone,na.rm = T)
plot(e_quakes$lat,xlab = "xaxis",ylab = "yaxis",col= "pink")
plot(e_quakes$long,e_quakes$mag , type = "l")
barplot(e_quakes[,5])
barplot(e_quakes$stations)
boxplot(e_quakes)
boxplot(e_quakes[,1:4])
boxplot(e_quakes$long)
hist(e_quakes[,4])
hist(e_quakes$lat)
par(mfrow=c(5,5), mar=c(2,1,2,3),bty="n")
plot(e_quakes$lat)
plot(e_quakes$long,e_quakes$mag)
barplot(e_quakes[5,5])
barplot(e_quakes$depth)
boxplot(e_quakes$stations)$out
hist(e_quakes[,3])
sd(e_quakes$lat , na.rm = T)
var(e_quakes$depth, na.rm = T)
skewness(e_quakes$long)
kurtosis(e_quakes$mag)
kurtosis(e_quakes$depth)
## 3
b1<- datasets::beaver1
summary(b1)
plot(b1$temp,b1$activ,xlab = "temp" ,ylab = "activ" ,col ="red",type = "l")
barplot(b1$temp,main = "Tempature",col = "red")
barplot(b1$activ,main = "Activity",col = "red")
barplot(b1$day, b1$activ, main = "Activity",col = "blue")
boxplot(b1$day,b1$activ)$out
boxplot(b1$activ)$out
hist(b1$day)
hist(b1$activ)
sd(b1$time,na.rm = T)
var(b1$temp)
